### ISSUE TITLE
uninitialized constant Gem::BundlerVersionFinder (NameError)

### ISSUE THREAD

**Issue by kevin-j-m** [TheGnarCo/gnarails#105]
Running gnarails from the CLI introduces an error on loading.

Version: 0.9.0
Ruby: 2.5.0

```
dev|⇒ gnarails new test-gnar
Traceback (most recent call last):
	22: from /Users/kevin/.gem/ruby/2.5.0/bin/gnarails:23:in `<main>'
	21: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	20: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:309:in `synchronize'
	19: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:311:in `block in activate_bin_path'
	18: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems.rb:239:in `finish_resolve'
	17: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	16: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1107:in `find_in_unresolved_tree'
	15: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1107:in `each'
	14: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1108:in `block in find_in_unresolved_tree'
	13: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2651:in `traverse'
	12: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2651:in `each'
	11: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2653:in `block in traverse'
	10: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb:302:in `to_specs'
	 9: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb:283:in `matching_specs'
	 8: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	 7: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1107:in `find_in_unresolved_tree'
	 6: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1107:in `each'
	 5: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1108:in `block in find_in_unresolved_tree'
	 4: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2651:in `traverse'
	 3: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2651:in `each'
	 2: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2653:in `block in traverse'
	 1: from /Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb:302:in `to_specs'
/Users/kevin/.rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb:283:in `matching_specs': uninitialized constant Gem::BundlerVersionFinder (NameError)
Did you mean?  Gem::BundlerVersionFinder
```

**Comment by kevin-j-m** [comment]
Based on [this issue](https://github.com/fastlane/fastlane/issues/11048) and [this issue](https://github.com/KrauseFx/xcode-install/issues/257), using `gem cleanup` locally resolved this for me.
