### ISSUE TITLE
Support Bundler 2

### ISSUE THREAD

**Issue by kevin-j-m** [TheGnarCo/gnarails#133]
Bundler 2.0 has been [released](https://bundler.io/blog/2019/01/03/announcing-bundler-2.html), which seems to be causing issues with this template file. We should investigate the underlying source of the problem and ensure that we can support the latest version of bundler.

**Comment by kevin-j-m** [comment]
Per @mikestone14 in his report on #137, here's what the result of running this template using Bundler 2:

```
Bundle complete! 36 Gemfile dependencies, 138 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
Post-install message from i18n:

HEADS UP! i18n 1.1 changed fallbacks to exclude default locale.
But that may break your application.

Please check your Rails app for 'config.i18n.fallbacks = true'.
If you're using I18n (>= 1.1.0) and Rails (< 5.2.2), this should be
'config.i18n.fallbacks = [I18n.default_locale]'.
If not, fallbacks will be broken in your app by I18n 1.1.x.

For more info see:
https://github.com/svenfuchs/i18n/releases/tag/v1.1.0

         run  bundle install
You must use Bundler 2 or greater with this lockfile.
         run  bundle exec spring binstub --all
You must use Bundler 2 or greater with this lockfile.
    generate  rspec:install
You must use Bundler 2 or greater with this lockfile.
      remove  .rspec
      create  .rspec
        gsub  spec/rails_helper.rb
Traceback (most recent call last):
        26: from /Users/michaelstone/.rbenv/versions/2.6.0/bin/rails:23:in `<main>'
        25: from /Users/michaelstone/.rbenv/versions/2.6.0/bin/rails:23:in `load'
        24: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/exe/rails:10:in `<top (required)>'
        23: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        22: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        21: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/cli.rb:18:in `<top (required)>'
        20: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/command.rb:46:in `invoke'
        19: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/command/base.rb:65:in `perform'
        18: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        17: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        16: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        15: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/commands/application/application_command.rb:26:in `perform'
        14: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        13: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
        12: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
        11: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
        10: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
         9: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
         8: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
         7: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
         6: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/generators/rails/app/app_generator.rb:482:in `run_after_bundle_callbacks'
         5: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/railties-5.2.2/lib/rails/generators/rails/app/app_generator.rb:482:in `each'
         4: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/gnarails-2.0.0/gnarly.rb:22:in `block in create_gnarly_rails_app'
         3: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/gnarails-2.0.0/gnarly.rb:79:in `setup_testing'
         2: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/gnarails-2.0.0/gnarly.rb:91:in `setup_rspec'
         1: from /Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:231:in `gsub_file'
/Users/michaelstone/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/thor-0.19.4/lib/thor/actions/file_manipulation.rb:231:in `binread': No such file or directory @ rb_sysopen - /Users/michaelstone/gnar/testapp/spec/rails_helper.rb (Errno::ENOENT)
```
